### ISSUE TITLE
Phase Angles Incorrect

### ISSUE THREAD

**Issue by LameLefty** [ABritInSpace/TransferCalculator-KSP2#15]
I tried to use this mod last night for a transfer from medium Jool orbit (circular, between the orbits of Laythe and Vall) back to Kerbin. The calculator gave me a desired phase angle of something like -409 degrees. It is unclear if this is simply the failure to subtract 360 degrees from the absolute value of the true desired phase angle, or some kind of other arithmetical error.  

Also a usability quirk - please add a “close” widget to the upper-right corner of the window so the display can be closed out without de-selecting the target body.

**Comment by ABritInSpace** [comment]
Fixed in latest.
