### ISSUE TITLE
Warp to transfer not working

### ISSUE THREAD

**Issue by schlosrat** [ABritInSpace/TransferCalculator-KSP2#17]
From a circular 400km orbit equatorial orbit about Kerbin, with Jool targeted, I clicked on Warp to transfer and observed the game warp to around the time of the transfer, slow the warp rate slightly, then back up to max rate for a year or so. Rinse and Repeat.

Two issues, really.

First, the warp to transfer may want to gradually step down the time warp as the transfer window approaches so that it doesn't overshoot and send you off to the next one.

Second, the only way to stop the madness is to click to stop button in the mod's window. It would be really nice if the "stop" effect could also be triggered by the player pausing or setting their timewarp to 1x. I think that would be more intuitive for some, and would probably be the right thing to do when a player tries to take control of their time warp rate.

**Comment by ABritInSpace** [comment]
1. Thanks for letting me know about this, I'll see how I can change it.
2. That's a very good usability idea, I'll try adding that as ankther way to cancel timewarp!

No ETA for these as I'm dealing with schoolwork at the moment and don't have access to the game to test fixes thoroughly!

**Comment by ABritInSpace** [comment]
Warp cancel feature added in latest. Haven't been able to thoroughly test the warping fix, but should be far more consistent now!
