### ISSUE TITLE
Transfer Window Open/Close

### ISSUE THREAD

**Issue by Scarecrow-71** [ABritInSpace/TransferCalculator-KSP2#18]
There is currently no way to bring up the transfer window apart from selecting a target, at which point the window opens automatically.  Conversely to this, there is no way to close the transfer window apart from deselecting the current target, at which point the window closes automatically.  We should have the option to open or close the window manually regardless of whether or not a target is selected.

**Comment by ABritInSpace** [comment]
Thanks, this has been flagged up already - I believe I have something working but haven't been able to test properly yet. This should come in the next update.

**Comment by ABritInSpace** [comment]
Added in the latest.
