### ISSUE TITLE
spacewarp.modlist info

### ISSUE THREAD

**Issue by schlosrat** [ABritInSpace/TransferCalculator-KSP2#6]
Nice mod! Thanks for putting it out there.

When I bring up the Mod menu from the loading screen there is no version or source info, and the KSP2 version looks like it's stuck with the default text "... - ... (can be * for no max version)"
Also the dependencies list is blank, should probably be none?

**Comment by ABritInSpace** [comment]
Which version are you using? In the latest (0.1.3] I tried to resolved this (for spacewarp 0.4.0). You are right though, there are no dependencies.

**Comment by ABritInSpace** [comment]
Fixed in latest.
